version: "2.3.0"
services:
  test_service:
    image: test_zone
    container_name: test
    ports:
    - 8080:1717
    volumes:
    - "/home/jackspades17/test_service:/opt/app"
    #- "$HOME/test_service:/opt/app"